data:
  name: "dclm-10B"
  path: "robbiegwaldd/dclm-10B"
  batch_size: 96
  micro_batch_size: 6
  val_set_size: 200
model:
  name: 'qwen3_gla'
  pretrained_model_name_or_path: 'Qwen/Qwen3-8B'
  max_length: 512
  # tokenizer
  add_eos_token: False
  # device_map: 'auto'

train:
  target_tokens: 100_000_000
  max_steps: null
  epochs: null
  optim: 'adamw_torch'
  lr_scheduler_type: cosine
  lr: 0.00001
  min_lr: 0.00001 

  max_grad_norm: 1.0
  output_dir: 'checkpoints_stage_1_qwen3'

  train_qk: False
  train_qk_lora: False
  train_v: False
  train_v_lora: False

  # Provide the path of the last checkpoint to resume training
  resume_from_checkpoint: 'None'

stage: 1