data:
  name: "dclm-10B"
  path: "robbiegwaldd/dclm-10B"
  batch_size: 96
  micro_batch_size: 12
  val_set_size: 200
model:
  name: 'rapid_distill_stage_1_qwen'
  pretrained_model_name_or_path: 'Qwen/Qwen2.5-7B-Instruct'
  max_length: 512
  # tokenizer
  add_eos_token: False
  device_map: 'auto'

train:
  target_tokens: 100_000_000
  max_steps: null
  epochs: null
  optim: 'adamw_torch'
  lr_scheduler_type: cosine_with_min_lr
  lr: 0.001
  min_lr: 0.00001 

  max_grad_norm: 1.0
  output_dir: 'checkpoints'

  train_qk: False
  train_qk_lora: False
  train_v: False
  train_v_lora: False