data:
  name: "dclm-10B"  # Or your long-context dataset
  path: "robbiegwaldd/dclm-10B" # Or your long-context dataset path
  batch_size: 96
  micro_batch_size: 2
  val_set_size: 200

model:
  name: 'qwen2'
  # This should be the base model config, it's used to load the right architecture
  pretrained_model_name_or_path: 'Qwen/Qwen2.5-7B-Instruct'
  # Increase context length for Stage 3
  max_length: 1024

train:
  # IMPORTANT: Set a new target or max_steps for this stage
  target_tokens: 500_000_000
  epochs: null
  max_steps: null
  optim: 'adamw_torch'
  lr_scheduler_type: constant
  lr: 0.00001
  min_lr: 0.00001
  max_grad_norm: 1
  output_dir: 'checkpoints_stage_3_1024'
  # This checkpoint is the PURIFIED student from Stage 2
  student_init_ckpt: 'checkpoints_stage_2_v6/checkpoint-5000'
  # Provide the path of the last checkpoint to resume training
  resume_from_checkpoint: None

# No 'distillation' section is needed for Stage 3

stage: 3